accounts/urls.py
from django.urls import path

from accounts import views

app_name = "account"

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.register, name='register')
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'

urlpatterns = [
    path('', views.detail, name='detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

django_online_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from shop.views import home_page, nevskiy, kurier, ViewKurier

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('accounts/', include('accounts.urls', namespace='accounts')),
                  path('cart/', include('cart.urls', namespace='cart')),
                  path('orders/', include('orders.urls', namespace='orders')),
                  path('', home_page, name='home_page'),
                  path('nevkiy/', nevskiy, name='nevskiy'),
                  path('kurier/', kurier, name='kurier'),
                  path('kurier/<int:pk>/', ViewKurier.as_view(), name='view_kurier'),
                  path('shop/', include('shop.urls', namespace='shop',)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from shop import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/<slug:slug>/', views.home, name='category_filter'),
    path('<slug:slug>/', views.product_detail, name='product_detail'),
]

templates/layouts/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="container-fluid">
            <div class="navbar-nav">
                <a class="nav-item nav-link" href="{% url 'shop:home' %}">Home</a>
                {% if request.user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:register' %}">Register</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>